version: '3'

services:

  mara-postgres:
    container_name: mara-postgres
    #    image: mara-postgres:dev-${PROJECT_NAME}
    image: mara-postgres:dev
    build: ./.scripts/docker/postgres/
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - "mara-postgres-data:/var/lib/postgresql/data"
  mara-app:
    container_name: mara-app
    #    image: mara-app:dev-${PROJECT_NAME}
    image: mara-app:dev
#    user: 1000:1000
    #    command: tail -f /dev/null # or multiple commands like sh -c ‘./.ssh-keys.sh && ...’
    build:
      context: .
      dockerfile: Dockerfile
#      args:
#        MARA_USER: ${MARA_USER}
        # SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    environment:
      POSTGRES_HOST: mara-postgres
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - ~/.ssh:/root/.ssh:ro # todo: ongoing
      - ./data:/mara/data
      - ./:/mara
    depends_on:
      - mara-postgres
    stdin_open: true
    tty: true

volumes:
  mara-postgres-data:
    driver: "local"
